### ISSUE TITLE
Stream inside the worker

### ISSUE THREAD

**Issue by kumavis** [max-mapper/workerstream#4]
Would you merge a PR for a utility for creating streams on the inside of the worker?
I feel like it is too small to be its own module and will often be used by consumers of workerstream

worker.js

``` javascript
var OriginStream = require('workerstream/inside')
module.exports = function(){
  var originStream = OriginStream(self)
  originStream.pipe(dataCruncher).pipe(originStream)
}
```

workerstream/inside.js

``` javascript
var Duplex = require('duplex')
// create duplex stream for communicating with
module.exports = function OriginStream(workerGlobal){
  var originStream = Duplex()
  workerGlobal.onmessage = function(message) {
    originStream._data(message.data)
  }
  originStream.on('_data', function (data) {
    workerGlobal.postMessage(data)
  })
  return originStream
}
```

PS: naming things is hard

**Comment by kumavis** [comment]
- There would need to be a couple more events handled by `workerstream/inside.js` (error states? I guess the browser will never disconnect from the worker, at least no event will be thrown)
- Likely don't need to pass the `workerGlobal` to `OriginStream`

**Comment by kumavis** [comment]
I suppose this is like asking to ask a question...
Prepping a PR that matches the `index.js` implementation

**Comment by tlrobinson** [comment]
Is there a way to get ParentStream to play nicely with webworker-threads? https://www.npmjs.com/package/webworker-threads

**Comment by kumavis** [comment]
@tlrobinson what issues are you running into?
I haven't tried it

**Comment by tlrobinson** [comment]
Well, Workers (including the webworker-threads implementation) don't have "require", so I imagine you'd need to use something like Browserify/WebWorkify to get ParentStream into the worker, but I'm not sure how to do that.

Maybe this is more of a question for WebWorkify. @maxogden ?

EDIT: Err sorry, WebWorkify would be @substack

**Comment by kumavis** [comment]
yea you can use WebWorkify to get ParentStream into a worker. play around with it and if you run into a problem. theres an example on the [readme](https://github.com/maxogden/workerstream/blob/master/readme.md). also read [webworkify's readme](https://github.com/substack/webworkify).

if you havent yet, take the time to learn browserify. its worth it.

you seem to be asking for help without attempting it yourself first, no?

**Comment by tlrobinson** [comment]
Browserify and WebWorkify are for the browser, no? I'm talking about using [node-webworker-threads](https://github.com/audreyt/node-webworker-threads) which is an implementation of WebWorkers for Node. There's no obvious way of using Browserify/WebWorkify in Node.

**Comment by kumavis** [comment]
Ah, got it. sounds like a question for the `webworker-threads` repo. Surprised they don't support require. You may be able to use browserify without node-native-modules shimming to get a single js file that you could put in the `webworker-thread`. Never done that before so not sure.

Anyways, the problem is well out of scope for this simple module. good luck!

**Comment by tlrobinson** [comment]
I actually did get it to work by just browserifying the worker before loading it (didn't even need WebWorkify). Thanks!

**Comment by kumavis** [comment]
@tlrobinson did you need any additional flags or anything?

**Comment by tlrobinson** [comment]
@kumavis Nope, and it even works with ES6 via Babel: https://gist.github.com/tlrobinson/730eee83dc135993810d

It's very very slow (relatively) to browserify/babelify, of course, so it would be better to pre-compile/cache the worker code.

**Comment by kumavis** [comment]
i forgot how much i enjoy this pattern. Thanks for reminding me. I made this today: https://github.com/kumavis/cryptographer/blob/master/storage/index.js#L11-L23

**Comment by tlrobinson** [comment]
@kumavis  Neat. This runs in the browser, not Node, right?

**Comment by kumavis** [comment]
correct.
